### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rakuishi** [rakuishi/Todo-Android#1]
- [x] xml レイアウトの id 名を `_textview` のように省略しない形にする
- [x] 文字数ゼロの時に確定できないようにする
- [x] Lolipop 以降で使える Transition を使ってみる
- [x] KeyDownEditText を Refine する
- [x] Otto を導入する
- [x] 依存性注入を導入する [Dagger 2](http://google.github.io/dagger/)
